### ISSUE TITLE
Depth-wise Multi-branch Dilated Convolution

### ISSUE THREAD

**Issue by chenjiachengzzz** [hlh981029/megcup-feedback#1]
您好，请问是还没有开源DMBDC这个模块的代码吗？

**Comment by hlh981029** [comment]
感谢提问！
multi-branch 的卷积没有直接写在 model 内部，而是在 build model 后统一 wrap 的，这样不需要修改模型本身的代码，具体逻辑可以参考 `searcher/search_engine.py` 中的 `wrap_model` 与 `searcher/operators.py` 中的 `Conv2dOp` 。

**Comment by lzyhha** [comment]
可以参考[Global2Local](https://github.com/ShangHua-Gao/G2L-search)的local_searcher部分

**Comment by lzyhha** [comment]
这是来自QQ邮箱的自动回复邮件。This is a automatic response.
